name: instabug_http_client
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  instabug:
    # git:
    #    url: https://github.com/Instabug/instabug-flutter.git
    #    ref: feature/networkLoggin
    path: ../Instabug-Flutter
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.