name: instabug_http_client
description: This package is an add on to instabug_flutter. It intercepts any requests performed 
            with http Package and sends them to the report that will be sent to the dashboard.
version: 1.1.0
author: Instabug <support@instabug.com>
homepage: https://github.com/Instabug/Instabug-Flutter#readme 

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  instabug_flutter: 
    git:
      url: https://github.com/FirstBlood-Mana/Instabug-Flutter
      ref: 7a2d89152c5bd1fac0b382e4e5c1d6ec156db9ae
  http: ^0.12.0+2
  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.